# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: blog/
    weight: 10
  - name: Documentation
    url: docs/
    weight: 20
  - name: Community
    url: community/
    weight: 40

sidebar:
  - identifier: more
    name: Still need help?
    params:
      type: separator
    weight: 1
  - identifier: community
    name: "Community"
    pageRef: "/community"
    weight: 2
